### ISSUE TITLE
Contao 4.4.2: Wizard class is missing

### ISSUE THREAD

**Issue by dmolineus** [netzmacht/contao-leaflet-geocode-widget#1]
Caused by https://github.com/contao/core-bundle/issues/997

**Comment by Toflar** [comment]
I think it's correct what's done in the core bundle. The widget explicitly requires `wizard` to always be present so the widget should make sure it's there and not rely on an external `tl_class` that was provided :)

**Comment by Toflar** [comment]
Just wrap it again:

```html
<div class="wizard">
    <input type="text"
           name="<?= $this->name ?>"
           id="ctrl_<?= $this->id ?>"
           class="tl_text tl_leaflet_geocode<?= $this->class ?>"
           value="<?= $this->value ?>"<?= $this->attributes ?>
           onfocus="Backend.getScrollOffset()"
    >
    <img src="bundles/leafletgeocodewidget/img/map.png" id="ctrl_<?= $this->id ?>_toggle">
</div>
```

Can I ask you to update the bundle? I need it 😄

**Comment by dmolineus** [comment]
> I think it's correct what's done in the core bundle. The widget explicitly requires wizard to always be present so the widget should make sure it's there and not rely on an external tl_class that was provided :)

It's definitely an BC introduced in a bugfix release. But it's not worth to discuss it. Applied the changes in branch https://github.com/netzmacht/contao-leaflet-geocode-widget/tree/hotfix/1.1.0 

Would be great if you could test it and confirm everything is working. Then I'll release v1.1.0.

**Comment by Toflar** [comment]
Works like a charm, you can release. But why 1.1.0? Why not 1.0.1? 😄

**Comment by dmolineus** [comment]
> Works like a charm, you can release. But why 1.1.0? Why not 1.0.1? 😄

Thanks. Just released it. Because of changed requirement of Contao.

**Comment by Toflar** [comment]
Would not qualify for a different minor version according to semver but anyway, that's no problem :) Thanks :)
